package handler

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/edsonmubezi/myapp/api/middleware"
	authRepo "github.com/edsonmubezi/myapp/internal/auth"
	"github.com/edsonmubezi/myapp/internal/identity"
	"github.com/edsonmubezi/myapp/internal/orgsettings"
	"github.com/edsonmubezi/myapp/internal/platform/email"
	"github.com/edsonmubezi/myapp/internal/platform/security"
	"github.com/edsonmubezi/myapp/internal/user"
	"github.com/edsonmubezi/myapp/pkg/auth"
	"github.com/edsonmubezi/myapp/pkg/cache"
	"github.com/edsonmubezi/myapp/pkg/validation"

	"golang.org/x/crypto/bcrypt"
)

type LoginRequest struct {
	Identifier string `json:"identifier" validate:"required"`
	Password   string `json:"password"   validate:"required"`
}

// loginIdentifier returns the display value for audit logs (email or TIN).
func (r *LoginRequest) loginIdentifier() string { return r.Identifier }

type LoginResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token" validate:"required"`
}

type RefreshTokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

type VerifyPasswordRequest struct {
	Password string `json:"password" validate:"required"`
}

// LoginResponseExtended includes additional security info
type LoginResponseExtended struct {
	AccessToken        string `json:"access_token,omitempty"`
	RefreshToken       string `json:"refresh_token,omitempty"`
	Requires2FA        bool   `json:"requires_2fa,omitempty"`
	TwoFactorMethod    string `json:"two_factor_method,omitempty"`
	SessionToken       string `json:"session_token,omitempty"`
	MustChangePassword bool   `json:"must_change_password,omitempty"`
}

const MaxLoginAttempts = 5

var userUseCase user.UserUseCase
var userRepo user.UserRepository
var refreshTokenRepo *authRepo.RefreshTokenRepository
var loginAttemptsRepo *authRepo.PostgresLoginAttemptsRepository
var securityService *security.Service
var orgSettingsRepo orgsettings.OrganizationSettingsRepository

func SetOrgSettingsRepository(repo orgsettings.OrganizationSettingsRepository) {
	orgSettingsRepo = repo
}

func SetUserUseCase(u user.UserUseCase) {
	userUseCase = u
}

func SetUserRepository(repo user.UserRepository) {
	userRepo = repo
}

func SetRefreshTokenRepository(repo *authRepo.RefreshTokenRepository) {
	refreshTokenRepo = repo
}

func SetLoginAttemptsRepository(repo *authRepo.PostgresLoginAttemptsRepository) {
	loginAttemptsRepo = repo
}

func SetSecurityService(svc *security.Service) {
	securityService = svc
}

// @Summary      Create User
// @Description  Create a new user account with email and password. Email must be unique within the organization.
// @Tags         Users
// @Security     BearerAuth
// @Accept       json
// @Produce      json
// @Param        user body user.User true "User details" example({"full_name":"John Doe","email":"john@example.com","password":"SecurePass123!","role_id":1,"organization_id":1})
// @Success      201 {object} SuccessResponse{data=user.User} "User created successfully"
// @Failure      400 {object} ErrorResponse "Invalid input or validation error"
// @Failure      409 {object} ErrorResponse "Email already exists"
// @Failure      500 {object} ErrorResponse "Internal server error"
// @Router       /api/users/create [post]
func CreateUserHandler(w http.ResponseWriter, r *http.Request) {
	parsedUser, validationErrors, err := middleware.ParseAndValidateBody[user.User](r)
	if err != nil {
		SendJSONResponse(w, http.StatusInternalServerError, "Something went wrong", nil)
		return
	}
	if validationErrors != nil {
		SendValidationErrors(w, validationErrors)
		return
	}
	if parsedUser == nil {
		SendJSONResponse(w, http.StatusBadRequest, "Invalid or missing request body", nil)
		return
	}
	parsedUser.Email = strings.TrimSpace(parsedUser.Email)
	parsedUser.FullName = strings.TrimSpace(parsedUser.FullName)

	existingUser, err := userUseCase.GetUserByEmail(r.Context(), parsedUser.Email)
	if err == nil && existingUser != nil {
		SendJSONResponse(w, http.StatusConflict, "Email is already in use", nil)
		return
	}

	// Auto-generate password if not provided
	autoGenerated := false
	rawPassword := parsedUser.Password
	if rawPassword == "" {
		tempPwd, genErr := generateTemporaryPassword(14)
		if genErr != nil {
			SendJSONResponse(w, http.StatusInternalServerError, "Failed to generate password", nil)
			return
		}
		rawPassword = tempPwd
		autoGenerated = true
	}

	// Validate password strength (skip if auto-generated — it already meets requirements)
	if !autoGenerated {
		passwordPolicy := validation.DefaultPasswordPolicy()
		if err := validation.ValidatePassword(rawPassword, passwordPolicy); err != nil {
			if validationErr, ok := err.(*validation.PasswordValidationError); ok {
				SendJSONResponse(w, http.StatusBadRequest, "Password does not meet security requirements", map[string]interface{}{
					"password_errors": validationErr.Errors,
				})
				return
			}
			SendJSONResponse(w, http.StatusBadRequest, err.Error(), nil)
			return
		}
	}

	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(rawPassword), bcrypt.DefaultCost)
	if err != nil {
		SendJSONResponse(w, http.StatusInternalServerError, "Failed to hash password", nil)
		return
	}
	parsedUser.Password = string(hashedPassword)
	parsedUser.MustChangePassword = true

	createdUser, err := userUseCase.CreateUser(r.Context(), parsedUser)
	if err != nil {
		SendJSONResponse(w, http.StatusInternalServerError, "Failed to create user", nil)
		return
	}

	// Send welcome email with credentials (branded HTML)
	if autoGenerated && emailResolver != nil {
		go func() {
			companyName := getEnv("COMPANY_NAME", "Microfinance")
			loginURL := getBaseURL() + "/login"

			branding := email.DefaultBranding()
			if Organize != nil {
				if bs, bErr := Organize.GetEmailBranding(r.Context(), createdUser.OrganizationID); bErr == nil && bs != nil {
					branding = email.EmailBranding{
						PrimaryColor:    bs.PrimaryColor,
						HeaderTextColor: bs.HeaderTextColor,
						AccentColor:     bs.AccentColor,
						FontFamily:      bs.FontFamily,
						FooterText:      bs.FooterText,
						SignOff:         bs.SignOff,
					}
				}
			}

			body, renderErr := email.RenderTemplate(email.TemplateWelcome, email.WelcomeData{
				UserName:     createdUser.FullName,
				LoginLink:    loginURL,
				CompanyName:  companyName,
				Email:        createdUser.Email,
				TempPassword: rawPassword,
			}, branding)
			if renderErr != nil {
				log.Printf("[ERROR] Failed to render welcome email template: %v", renderErr)
				return
			}

			emailSvc := emailResolver.ForOrg(r.Context(), createdUser.OrganizationID)
			if sendErr := emailSvc.SendEmail(r.Context(), []string{createdUser.Email}, "Welcome to "+companyName+" - Your Account Credentials", body, true); sendErr != nil {
				log.Printf("[ERROR] Failed to send welcome email to %s: %v", createdUser.Email, sendErr)
			}
		}()
	}

	createdUser.Password = ""
	SendJSONResponse(w, http.StatusCreated, "User created successfully", createdUser)
}

// @Summary      User Login
// @Description  Authenticates user with email and password, returns access and refresh tokens. Supports multi-tenant architecture.
// @Tags         Authentication
// @Accept       json
// @Produce      json
// @Param        credentials body LoginRequest true "Login credentials" example({"email":"user@example.com","password":"SecurePass123!"})
// @Success      200 {object} AuthSuccessResponse "Login successful with tokens"
// @Failure      400 {object} ErrorResponse "Invalid request format"
// @Failure      401 {object} ErrorResponse "Invalid credentials"
// @Failure      403 {object} ErrorResponse "Account is deactivated or locked"
// @Failure      500 {object} ErrorResponse "Internal server error"
// @Router       /api/login [post]
func LoginHandler(w http.ResponseWriter, r *http.Request) {
	req, validationErrors, err := middleware.ParseAndValidateBody[LoginRequest](r)
	if err != nil {
		SendJSONResponse(w, http.StatusInternalServerError, "Something went wrong", nil)
		return
	}
	if validationErrors != nil {
		SendValidationErrors(w, validationErrors)
		return
	}

	// Get request metadata for logging
	ipAddress := getClientIPFromRequest(r)
	userAgent := r.Header.Get("User-Agent")

	identifier := strings.TrimSpace(req.Identifier)

	// Helper function to log login attempts (PostgreSQL)
	logLoginAttempt := func(userID *int64, tenantID *int64, success bool, reason string) {
		// Log to PostgreSQL (existing audit trail)
		if loginAttemptsRepo != nil {
			err := loginAttemptsRepo.Create(r.Context(), authRepo.LoginAttemptInput{
				UserID:        userID,
				Email:         identifier,
				IPAddress:     ipAddress,
				UserAgent:     userAgent,
				Success:       success,
				FailureReason: reason,
			})
			if err != nil {
				log.Printf("Error logging login attempt: %v", err)
			}
		}

		// Log to PostgreSQL security events (enhanced security monitoring)
		if securityService != nil {
			if success && userID != nil && tenantID != nil {
				// Record successful login
				go func() {
					if err := securityService.RecordLoginSuccess(r.Context(), *tenantID, *userID, identifier, ipAddress, userAgent); err != nil {
						log.Printf("Error recording security event (login success): %v", err)
					}
				}()
			} else if !success {
				// Record failed login
				go func() {
					if err := securityService.RecordLoginFailed(r.Context(), tenantID, identifier, reason, ipAddress, userAgent); err != nil {
						log.Printf("Error recording security event (login failed): %v", err)
					}
				}()
			}
		}
	}

	// Lookup user by email
	var foundUser *user.User

	if userRepo != nil {
		foundUser, err = userRepo.GetUserByEmailWithSecurity(r.Context(), identifier)
	} else {
		foundUser, err = userUseCase.GetUserByEmail(r.Context(), identifier)
	}

	if err != nil || foundUser == nil {
		log.Printf("[LOGIN DEBUG] User lookup failed for identifier=%q err=%v", identifier, err)
		logLoginAttempt(nil, nil, false, "user_not_found")
		SendJSONResponse(w, http.StatusUnauthorized, "Invalid credentials", nil)
		return
	}

	// Check if account is deactivated
	if !foundUser.ActiveStatus {
		logLoginAttempt(&foundUser.ID, &foundUser.OrganizationID, false, "account_inactive")
		SendJSONResponse(w, http.StatusForbidden, "Account is deactivated. Please contact your administrator.", nil)
		return
	}

	// Check if account is locked
	if foundUser.IsLocked() {
		logLoginAttempt(&foundUser.ID, &foundUser.OrganizationID, false, "account_locked")

		// Record account locked event to security service
		if securityService != nil {
			go func() {
				if err := securityService.RecordAccountLocked(r.Context(), foundUser.OrganizationID, foundUser.ID, foundUser.Email, "login_attempt_while_locked", ipAddress); err != nil {
					log.Printf("Error recording security event (account locked): %v", err)
				}
			}()
		}

		SendJSONResponse(w, http.StatusForbidden, "Account is locked due to too many failed login attempts. Please contact your administrator to unlock your account.", nil)
		return
	}

	// Verify password
	if err := bcrypt.CompareHashAndPassword([]byte(foundUser.Password), []byte(req.Password)); err != nil {
		// Password is incorrect - increment failed attempts
		if userRepo != nil {
			failedCount, err := userRepo.IncrementFailedAttempts(r.Context(), foundUser.ID)
			if err != nil {
				log.Printf("Error incrementing failed attempts: %v", err)
			}

			// Check if we should lock the account
			if failedCount >= MaxLoginAttempts {
				err = userRepo.LockAccount(r.Context(), foundUser.ID, fmt.Sprintf("Too many failed login attempts (%d)", failedCount))
				if err != nil {
					log.Printf("Error locking account: %v", err)
				}
				logLoginAttempt(&foundUser.ID, &foundUser.OrganizationID, false, "account_locked_after_max_attempts")

				// Record account locked event to security service
				if securityService != nil {
					go func() {
						if err := securityService.RecordAccountLocked(r.Context(), foundUser.OrganizationID, foundUser.ID, foundUser.Email, fmt.Sprintf("max_failed_attempts_%d", failedCount), ipAddress); err != nil {
							log.Printf("Error recording security event (account locked): %v", err)
						}
					}()
				}

				SendJSONResponse(w, http.StatusForbidden, "Account has been locked due to too many failed login attempts. Please contact your administrator.", nil)
				return
			}

			// Inform user of remaining attempts
			remainingAttempts := MaxLoginAttempts - failedCount
			logLoginAttempt(&foundUser.ID, &foundUser.OrganizationID, false, "invalid_password")
			SendJSONResponse(w, http.StatusUnauthorized, fmt.Sprintf("Invalid credentials. %d attempt(s) remaining before account lockout.", remainingAttempts), nil)
			return
		}

		logLoginAttempt(&foundUser.ID, &foundUser.OrganizationID, false, "invalid_password")
		SendJSONResponse(w, http.StatusUnauthorized, "Invalid credentials", nil)
		return
	}

	// Login successful - reset failed attempts
	if userRepo != nil {
		if err := userRepo.ResetFailedAttempts(r.Context(), foundUser.ID); err != nil {
			log.Printf("Error resetting failed attempts: %v", err)
		}
	}

	// Clear rate limit on successful login
	rateLimitKey := fmt.Sprintf("ratelimit:login:%s", middleware.GetClientIP(r))
	middleware.ClearRateLimit(r.Context(), rateLimitKey)

	// Log successful login attempt (password verified)
	logLoginAttempt(&foundUser.ID, &foundUser.OrganizationID, true, "")

	// In development, skip 2FA and issue tokens directly
	appEnv := strings.ToLower(os.Getenv("APP_ENV"))
	if appEnv != "production" {
		roleName := ""
		if foundUser.Role != nil {
			roleName = foundUser.Role.Name
		}

		accessToken, err := auth.GenerateAccessToken(foundUser.ID, foundUser.Email, foundUser.OrganizationID, roleName, foundUser.FullName)
		if err != nil {
			SendJSONResponse(w, http.StatusInternalServerError, "Failed to generate access token", nil)
			return
		}
		refreshToken, err := auth.GenerateRefreshToken(foundUser.ID, foundUser.OrganizationID)
		if err != nil {
			SendJSONResponse(w, http.StatusInternalServerError, "Failed to generate refresh token", nil)
			return
		}

		// Store refresh token if repository available
		if refreshTokenRepo != nil {
			tokenHash := auth.HashToken(refreshToken)
			expiresAt := time.Now().Add(7 * 24 * time.Hour)
			userAgent := r.Header.Get("User-Agent")
			deviceInfo := fmt.Sprintf("IP: %s, UA: %s", ipAddress, userAgent)
			if _, err := refreshTokenRepo.StoreRefreshToken(r.Context(), foundUser.ID, tokenHash, expiresAt, deviceInfo, ipAddress, userAgent); err != nil {
				log.Printf("Error storing refresh token: %v", err)
			}
		}

		// Check if user must change password (first login)
		if foundUser.MustChangePassword {
			SendJSONResponse(w, http.StatusOK, "Login successful. Password change required.", LoginResponseExtended{
				AccessToken:        accessToken,
				RefreshToken:       refreshToken,
				MustChangePassword: true,
			})
			return
		}

		SendJSONResponse(w, http.StatusOK, "Login successful", LoginResponseExtended{
			AccessToken:  accessToken,
			RefreshToken: refreshToken,
		})
		return
	}

	// Production: Mandatory login OTP — every login requires verification.
	// If user has 2FA enabled with a preferred method, use it; otherwise default to email.
	sessionToken, err := auth.Generate2FASessionToken(foundUser.ID, foundUser.OrganizationID)
	if err != nil {
		SendJSONResponse(w, http.StatusInternalServerError, "Failed to generate session token", nil)
		return
	}

	twoFactorMethod := "email" // default: mandatory email OTP for all users
	if foundUser.TwoFactorEnabled && foundUser.TwoFactorMethod != nil {
		twoFactorMethod = *foundUser.TwoFactorMethod
	}

	// For email/SMS methods, generate and send OTP code automatically
	if twoFactorMethod == "email" || twoFactorMethod == "sms" {
		if totpService != nil {
			method := authRepo.TwoFactorMethod(twoFactorMethod)
			code, err := totpService.GenerateOTPCode(r.Context(), foundUser.ID, method, 10)
			if err != nil {
				log.Printf("Error generating OTP code: %v", err)
			} else if twoFactorMethod == "email" && emailResolver != nil {
				subject := "Your Microfinance Verification Code"
				content := "Your verification code is: " + code + "\n\nThis code will expire in 10 minutes."
				emailSvc := emailResolver.ForOrg(r.Context(), foundUser.OrganizationID)
				if err := emailSvc.SendEmail(r.Context(), []string{foundUser.Email}, subject, content, false); err != nil {
					log.Printf("Error sending verification email: %v", err)
				}
			}
			// SMS sending will be implemented with SMS provider
		}
	}
	// For TOTP method, no code is sent — user uses their authenticator app

	SendJSONResponse(w, http.StatusOK, "Verification required", LoginResponseExtended{
		Requires2FA:     true,
		TwoFactorMethod: twoFactorMethod,
		SessionToken:    sessionToken,
	})
}

// @Summary      Refresh Access Token
// @Description  Generates new access and refresh tokens using a valid refresh token. Use this when access token expires.
// @Tags         Authentication
// @Accept       json
// @Produce      json
// @Param        request body RefreshTokenRequest true "Refresh token" example({"refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."})
// @Success      200 {object} AuthSuccessResponse "New tokens generated successfully"
// @Failure      400 {object} ErrorResponse "Invalid request format"
// @Failure      401 {object} ErrorResponse "Invalid or expired refresh token"
// @Failure      500 {object} ErrorResponse "Internal server error"
// @Router       /api/refresh [post]
func RefreshTokenHandler(w http.ResponseWriter, r *http.Request) {
	req, validationErrors, err := middleware.ParseAndValidateBody[RefreshTokenRequest](r)
	if err != nil {
		SendJSONResponse(w, http.StatusInternalServerError, "Something went wrong", nil)
		return
	}
	if validationErrors != nil {
		SendValidationErrors(w, validationErrors)
		return
	}

	// Validate the refresh token JWT structure
	claims, err := auth.ValidateToken(req.RefreshToken)
	if err != nil {
		SendJSONResponse(w, http.StatusUnauthorized, "Invalid or expired refresh token", nil)
		return
	}

	// Check token rotation database if repository is available
	if refreshTokenRepo != nil {
		// Hash the incoming refresh token
		tokenHash := auth.HashToken(req.RefreshToken)

		// Check if token exists in database and isn't revoked
		storedToken, err := refreshTokenRepo.GetRefreshToken(r.Context(), tokenHash)
		if err != nil {
			log.Printf("Error retrieving refresh token: %v", err)
			SendJSONResponse(w, http.StatusInternalServerError, "Token validation failed", nil)
			return
		}

		// Token not found in database
		if storedToken == nil {
			SendJSONResponse(w, http.StatusUnauthorized, "Invalid refresh token", nil)
			return
		}

		// Check if token has been revoked
		if storedToken.RevokedAt != nil {
			// SECURITY: Token reuse detection - if token was already replaced, revoke all user tokens
			if storedToken.ReplacedByTokenID != nil {
				log.Printf("SECURITY ALERT: Token reuse detected for user %d. Revoking all tokens.", claims.UserID)
				if err := refreshTokenRepo.RevokeAllUserTokens(r.Context(), claims.UserID); err != nil {
					log.Printf("Error revoking all user tokens: %v", err)
				}
				SendJSONResponse(w, http.StatusUnauthorized, "Token reuse detected. All sessions have been terminated for security.", nil)
				return
			}
			SendJSONResponse(w, http.StatusUnauthorized, "Refresh token has been revoked", nil)
			return
		}

		// Check if token has expired
		if storedToken.ExpiresAt.Before(time.Now()) {
			SendJSONResponse(w, http.StatusUnauthorized, "Refresh token has expired", nil)
			return
		}
	}

	// Get user from database to ensure they still exist and are active
	user, err := userUseCase.GetUserByID(r.Context(), claims.UserID, claims.OrganizationID)
	if err != nil || user == nil {
		SendJSONResponse(w, http.StatusUnauthorized, "User not found", nil)
		return
	}

	if !user.ActiveStatus {
		SendJSONResponse(w, http.StatusForbidden, "Account is deactivated", nil)
		return
	}

	// Check if account is locked
	if user.IsLocked() {
		SendJSONResponse(w, http.StatusForbidden, "Account is locked. Please contact your administrator.", nil)
		return
	}

	// Get role name
	roleName := ""
	if user.Role != nil {
		roleName = user.Role.Name
	}

	// Generate new access token
	accessToken, err := auth.GenerateAccessToken(user.ID, user.Email, user.OrganizationID, roleName, user.FullName)
	if err != nil {
		SendJSONResponse(w, http.StatusInternalServerError, "Failed to generate access token", nil)
		return
	}

	// Generate new refresh token
	newRefreshToken, err := auth.GenerateRefreshToken(user.ID, user.OrganizationID)
	if err != nil {
		SendJSONResponse(w, http.StatusInternalServerError, "Failed to generate refresh token", nil)
		return
	}

	// Store new refresh token and revoke old one (if repository available)
	if refreshTokenRepo != nil {
		// Hash the new refresh token for storage
		newTokenHash := auth.HashToken(newRefreshToken)

		// Calculate expiration (7 days from now, same as token generation)
		expiresAt := time.Now().Add(7 * 24 * time.Hour)

		// Get device info from request
		userAgent := r.Header.Get("User-Agent")
		ipAddress := getClientIPFromRequest(r)
		deviceInfo := fmt.Sprintf("IP: %s, UA: %s", ipAddress, userAgent)

		// Store new refresh token
		newTokenID, err := refreshTokenRepo.StoreRefreshToken(
			r.Context(),
			user.ID,
			newTokenHash,
			expiresAt,
			deviceInfo,
			ipAddress,
			userAgent,
		)
		if err != nil {
			log.Printf("Error storing new refresh token: %v", err)
			// Continue anyway - token generation succeeded
		}

		// Revoke old refresh token
		oldTokenHash := auth.HashToken(req.RefreshToken)
		if err := refreshTokenRepo.RevokeToken(r.Context(), oldTokenHash, &newTokenID); err != nil {
			log.Printf("Error revoking old refresh token: %v", err)
			// Continue anyway
		}
	}

	SendJSONResponse(w, http.StatusOK, "Token refreshed successfully", RefreshTokenResponse{
		AccessToken:  accessToken,
		RefreshToken: newRefreshToken,
	})
}

// @Summary      Change Password
// @Description  Changes the password for the authenticated user. Requires current password verification.
// @Tags         Authentication
// @Security     BearerAuth
// @Accept       json
// @Produce      json
// @Param        request body ChangePasswordRequest true "Current and new password" example({"current_password":"OldPass123!","new_password":"NewSecurePass123!"})
// @Success      200 {object} MessageResponse "Password changed successfully"
// @Failure      400 {object} ErrorResponse "Invalid request or weak password"
// @Failure      401 {object} ErrorResponse "Unauthorized or incorrect current password"
// @Failure      404 {object} ErrorResponse "User not found"
// @Failure      500 {object} ErrorResponse "Internal server error"
// @Router       /api/change-password [put]
func ChangePasswordHandler(w http.ResponseWriter, r *http.Request) {
	// Get authenticated user ID from JWT context
	authUser, err := identity.Require(r.Context())
	if err != nil {
		http.Error(w, "Unauthorized", http.StatusUnauthorized)
		return
	}

	var req ChangePasswordRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	// Validate required fields
	if req.CurrentPassword == "" || req.NewPassword == "" {
		http.Error(w, "Current password and new password are required", http.StatusBadRequest)
		return
	}

	// Validate password strength with comprehensive policy
	passwordPolicy := validation.DefaultPasswordPolicy()
	if err := validation.ValidatePassword(req.NewPassword, passwordPolicy); err != nil {
		if validationErr, ok := err.(*validation.PasswordValidationError); ok {
			SendJSONResponse(w, http.StatusBadRequest, "Password does not meet security requirements", map[string]interface{}{
				"password_errors": validationErr.Errors,
			})
			return
		}
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Get current user to verify current password
	currentUser, err := userUseCase.GetUserByID(r.Context(), authUser.UserID, authUser.OrganizationID)
	if err != nil {
		log.Printf("Failed to get user: %v", err)
		http.Error(w, "User not found", http.StatusNotFound)
		return
	}

	// Verify current password
	if err := bcrypt.CompareHashAndPassword([]byte(currentUser.Password), []byte(req.CurrentPassword)); err != nil {
		http.Error(w, "Current password is incorrect", http.StatusUnauthorized)
		return
	}

	// Hash new password
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(req.NewPassword), bcrypt.DefaultCost)
	if err != nil {
		log.Printf("Failed to hash password: %v", err)
		http.Error(w, "Failed to encrypt password", http.StatusInternalServerError)
		return
	}

	// Change password (only for authenticated user)
	if err := userUseCase.ChangePassword(r.Context(), authUser.UserID, authUser.OrganizationID, string(hashedPassword)); err != nil {
		log.Printf("Failed to change password: %v", err)
		http.Error(w, "Failed to change password", http.StatusInternalServerError)
		return
	}

	// Clear must_change_password flag if set
	if userRepo != nil {
		if err := userRepo.SetMustChangePassword(r.Context(), authUser.UserID, false); err != nil {
			log.Printf("Warning: Failed to clear must_change_password flag: %v", err)
			// Don't fail - password was changed successfully
		}
	}

	// Blacklist all existing tokens for this user (forces re-login)
	if err := auth.BlacklistUserTokens(r.Context(), authUser.UserID); err != nil {
		log.Printf("Warning: Failed to blacklist user tokens after password change: %v", err)
		// Don't fail the request, password was changed successfully
	}

	SendJSONResponse(w, http.StatusOK, "Password changed successfully. Please log in again with your new password.", nil)
}

// @Summary      User Logout
// @Description  Logs out the authenticated user by revoking their current access token. Forces re-authentication for subsequent requests.
// @Tags         Authentication
// @Security     BearerAuth
// @Produce      json
// @Success      200 {object} MessageResponse "Logged out successfully"
// @Failure      401 {object} ErrorResponse "Unauthorized - invalid or missing token"
// @Failure      500 {object} ErrorResponse "Internal server error"
// @Router       /api/logout [post]
func LogoutHandler(w http.ResponseWriter, r *http.Request) {
	// Get the current token from Authorization header
	authHeader := r.Header.Get("Authorization")
	tokenString := strings.TrimSpace(strings.TrimPrefix(authHeader, "Bearer "))
	if tokenString == "" {
		SendJSONResponse(w, http.StatusUnauthorized, "Missing token", nil)
		return
	}

	// Validate token to get claims
	claims, err := auth.ValidateToken(tokenString)
	if err != nil {
		SendJSONResponse(w, http.StatusUnauthorized, "Invalid token", nil)
		return
	}

	// Blacklist the current access token
	if claims.ExpiresAt != nil {
		if err := auth.BlacklistToken(r.Context(), tokenString, claims.ExpiresAt.Time); err != nil {
			log.Printf("Warning: Failed to blacklist token on logout: %v", err)
		}
	}

	// Blacklist ALL tokens for this user (prevents refresh token from generating new access tokens)
	if err := auth.BlacklistUserTokens(r.Context(), claims.UserID); err != nil {
		log.Printf("Warning: Failed to blacklist user tokens on logout: %v", err)
	}

	// Revoke all refresh tokens in the database
	if refreshTokenRepo != nil {
		if err := refreshTokenRepo.RevokeAllUserTokens(r.Context(), claims.UserID); err != nil {
			log.Printf("Warning: Failed to revoke refresh tokens on logout: %v", err)
		}
	}

	// Clear rate limit counter on logout so user can log back in immediately
	rateLimitKey := fmt.Sprintf("ratelimit:login:%s", middleware.GetClientIP(r))
	middleware.ClearRateLimit(r.Context(), rateLimitKey)

	SendJSONResponse(w, http.StatusOK, "Logged out successfully", nil)
}

// @Summary      Verify Password
// @Description  Verifies the password for the authenticated user. Used for lock screen unlock.
// @Tags         Authentication
// @Security     BearerAuth
// @Accept       json
// @Produce      json
// @Param        request body VerifyPasswordRequest true "Password to verify"
// @Success      200 {object} MessageResponse "Password verified successfully"
// @Failure      400 {object} ErrorResponse "Invalid request"
// @Failure      401 {object} ErrorResponse "Unauthorized or incorrect password"
// @Failure      500 {object} ErrorResponse "Internal server error"
// @Router       /api/auth/verify-password [post]
func VerifyPasswordHandler(w http.ResponseWriter, r *http.Request) {
	// Get authenticated user ID from JWT context
	authUser, err := identity.Require(r.Context())
	if err != nil {
		SendJSONResponse(w, http.StatusUnauthorized, "Unauthorized", nil)
		return
	}

	var req VerifyPasswordRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		SendJSONResponse(w, http.StatusBadRequest, "Invalid request body", nil)
		return
	}

	if req.Password == "" {
		SendJSONResponse(w, http.StatusBadRequest, "Password is required", nil)
		return
	}

	// Get current user
	currentUser, err := userUseCase.GetUserByID(r.Context(), authUser.UserID, authUser.OrganizationID)
	if err != nil {
		log.Printf("Failed to get user for password verification: %v", err)
		SendJSONResponse(w, http.StatusInternalServerError, "Failed to verify password", nil)
		return
	}

	// Verify password
	if err := bcrypt.CompareHashAndPassword([]byte(currentUser.Password), []byte(req.Password)); err != nil {
		SendJSONResponse(w, http.StatusUnauthorized, "Incorrect password", nil)
		return
	}

	SendJSONResponse(w, http.StatusOK, "Password verified successfully", nil)
}

// SessionConfigHandler returns session configuration for the authenticated user's organization.
// Used by the frontend to know the idle lock timeout. Cached in Redis.
func SessionConfigHandler(w http.ResponseWriter, r *http.Request) {
	authUser, err := identity.Require(r.Context())
	if err != nil {
		SendJSONResponse(w, http.StatusUnauthorized, "Unauthorized", nil)
		return
	}

	ctx := r.Context()

	// Try Redis cache first (org settings usecase caches the full object)
	if cached, err := cache.Get[orgsettings.OrganizationSettings](ctx, cache.OrgSettingsKey(authUser.OrganizationID)); err == nil && cached != nil {
		idleTimeout := 15
		if cached.SessionLockTimeoutMinutes > 0 {
			idleTimeout = cached.SessionLockTimeoutMinutes
		}
		SendJSONResponse(w, http.StatusOK, "Session config", map[string]interface{}{
			"idle_timeout_minutes": idleTimeout,
		})
		return
	}

	// Cache miss — fall through to DB
	idleTimeoutMinutes := 15 // default

	if orgSettingsRepo != nil {
		settings, err := orgSettingsRepo.GetOrgSettingsByOrganizationID(ctx, authUser.OrganizationID)
		if err != nil {
			log.Printf("SessionConfigHandler: failed to get org settings: %v", err)
		} else if settings != nil {
			// Populate the cache for next time
			cache.Set(ctx, cache.OrgSettingsKey(authUser.OrganizationID), settings, 10*time.Minute)
			if settings.SessionLockTimeoutMinutes > 0 {
				idleTimeoutMinutes = settings.SessionLockTimeoutMinutes
			}
		}
	}

	SendJSONResponse(w, http.StatusOK, "Session config", map[string]interface{}{
		"idle_timeout_minutes": idleTimeoutMinutes,
	})
}

// validatePasswordStrength validates password complexity requirements
func validatePasswordStrength(password string) error {
	if len(password) < 12 {
		return fmt.Errorf("password must be at least 12 characters long")
	}

	var (
		hasUpper   = regexp.MustCompile(`[A-Z]`).MatchString(password)
		hasLower   = regexp.MustCompile(`[a-z]`).MatchString(password)
		hasNumber  = regexp.MustCompile(`[0-9]`).MatchString(password)
		hasSpecial = regexp.MustCompile(`[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]`).MatchString(password)
	)

	if !hasUpper || !hasLower || !hasNumber || !hasSpecial {
		return fmt.Errorf("password must contain uppercase, lowercase, number, and special character")
	}

	// Check against common passwords
	commonPasswords := []string{"password", "123456", "12345678", "qwerty", "admin", "letmein"}
	lowerPass := strings.ToLower(password)
	for _, common := range commonPasswords {
		if lowerPass == common || strings.Contains(lowerPass, common) {
			return fmt.Errorf("password is too common")
		}
	}

	return nil
}

// getClientIPFromRequest extracts the real client IP from the request
// Checks X-Forwarded-For and X-Real-IP headers for proxy support
func getClientIPFromRequest(r *http.Request) string {
	// Check X-Forwarded-For header (set by proxies)
	if xff := r.Header.Get("X-Forwarded-For"); xff != "" {
		// X-Forwarded-For can contain multiple IPs, use the first one
		ips := strings.Split(xff, ",")
		if len(ips) > 0 {
			return strings.TrimSpace(ips[0])
		}
	}

	// Check X-Real-IP header
	if xri := r.Header.Get("X-Real-IP"); xri != "" {
		return xri
	}

	// Fall back to RemoteAddr
	ip := r.RemoteAddr
	// Remove port if present
	if idx := strings.LastIndex(ip, ":"); idx != -1 {
		ip = ip[:idx]
	}

	return ip
}
