apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "request_id=(\\S+)"
          name: RequestID
          url: "$${__value.raw}"
    editable: false

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ['request_id']
        filterByTraceID: false
        filterBySpanID: false
      serviceMap:
        datasourceUid: tempo
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki
    editable: false

  - name: PostgreSQL-Audit
    type: postgres
    access: proxy
    url: db:5432
    database: myapp
    user: user
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1300
      timescaledb: false
    editable: false
