#!/bin/bash
# =============================================================================
# EkklesiaHR Quick Setup Script
# =============================================================================
# This script helps set up EkklesiaHR for the first time
# Usage: ./scripts/setup.sh [development|production]

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default environment
ENV="${1:-development}"

echo -e "${BLUE}"
echo "=============================================="
echo "       EkklesiaHR Setup Script"
echo "=============================================="
echo -e "${NC}"

# Function to generate random string
generate_secret() {
    openssl rand -base64 "$1" 2>/dev/null || head -c "$1" /dev/urandom | base64
}

# Check prerequisites
echo -e "${YELLOW}Checking prerequisites...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed${NC}"
    exit 1
fi

if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
    echo -e "${RED}Error: Docker Compose is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Docker and Docker Compose found${NC}"

# Create .env file if it doesn't exist
if [ ! -f ".env" ]; then
    echo -e "${YELLOW}Creating .env file...${NC}"

    # Generate secure secrets
    JWT_SECRET=$(generate_secret 64)
    SECRET_KEY=$(generate_secret 32)
    POSTGRES_PASSWORD=$(generate_secret 24)
    MONGODB_PASSWORD=$(generate_secret 24)

    cat > .env << EOF
# =============================================================================
# EkklesiaHR Environment Configuration
# =============================================================================
# Generated by setup script on $(date)

# Database
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_USER=user
POSTGRES_DB=myapp

# Security Keys (Auto-generated - DO NOT SHARE)
JWT_SECRET=${JWT_SECRET}
SECRET_KEY=${SECRET_KEY}

# MongoDB
MONGODB_USERNAME=ekklesia
MONGODB_PASSWORD=${MONGODB_PASSWORD}

# Application
PORT=8080
BASE_URL=http://localhost:8080
RUNTIME_ENV=${ENV}
CORS_ALLOWED_ORIGIN=http://localhost

# Redis
REDIS_ENABLED=true
REDIS_HOST=redis
REDIS_PORT=6379

# Logging
LOG_LEVEL=info
LOG_FORMAT=json

# Storage
STORAGE_TYPE=local
ENABLE_FILE_UPLOAD=true
EOF

    echo -e "${GREEN}✓ Created .env file with secure secrets${NC}"
else
    echo -e "${YELLOW}! .env file already exists, skipping creation${NC}"
fi

# Choose compose file based on environment
if [ "$ENV" = "production" ]; then
    COMPOSE_FILE="docker-compose.fullstack.yml"
    COMPOSE_PROFILE="--profile production"
    echo -e "${BLUE}Using production configuration${NC}"
else
    COMPOSE_FILE="docker-compose.fullstack.yml"
    COMPOSE_PROFILE=""
    echo -e "${BLUE}Using development configuration${NC}"
fi

# Pull/Build images
echo -e "${YELLOW}Building Docker images...${NC}"
docker-compose -f "$COMPOSE_FILE" $COMPOSE_PROFILE build

# Start services
echo -e "${YELLOW}Starting services...${NC}"
docker-compose -f "$COMPOSE_FILE" $COMPOSE_PROFILE up -d

# Wait for database to be ready
echo -e "${YELLOW}Waiting for database to be ready...${NC}"
sleep 10

# Check if database is ready
MAX_ATTEMPTS=30
ATTEMPTS=0
while [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
    if docker-compose -f "$COMPOSE_FILE" exec -T db pg_isready -U user -d myapp > /dev/null 2>&1; then
        echo -e "${GREEN}✓ Database is ready${NC}"
        break
    fi
    ATTEMPTS=$((ATTEMPTS + 1))
    echo "Waiting for database... ($ATTEMPTS/$MAX_ATTEMPTS)"
    sleep 2
done

if [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; then
    echo -e "${RED}Warning: Database may not be ready${NC}"
fi

# Run migrations
echo -e "${YELLOW}Running database migrations...${NC}"
docker-compose -f "$COMPOSE_FILE" exec -T app /app/migrate up

echo -e "${GREEN}"
echo "=============================================="
echo "       Setup Complete!"
echo "=============================================="
echo -e "${NC}"
echo ""
echo "Access your application at:"
echo -e "  ${BLUE}Frontend:${NC} http://localhost"
echo -e "  ${BLUE}API:${NC}      http://localhost:8080"
echo -e "  ${BLUE}Health:${NC}   http://localhost:8080/health"
echo ""
echo "Useful commands:"
echo "  View logs:     docker-compose -f $COMPOSE_FILE logs -f"
echo "  Stop:          docker-compose -f $COMPOSE_FILE down"
echo "  Restart:       docker-compose -f $COMPOSE_FILE restart"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Create your first organization at http://localhost/register"
echo "  2. Configure email settings in .env for notifications"
echo "  3. See DEPLOYMENT.md for production deployment guide"
echo ""
